### ISSUE TITLE
Crash your Opponent

### ISSUE THREAD

**Issue by Robin481** [scg-unibe-ch/ese2017-team8#20]
Hallo zusammen

Also hier die Bugs (oder ähnlich ^^) die wir gefunden haben:
1: Man kann bei der Größe von Paketen Strings eingeben und es gibt keinen Fehler sondern setzt die Werte per Default auf 0.
2: Auch kann man Negative Zahlen eingeben die einfach akzeptiert werden ohne Fehler.
3: Login Namen sind nicht Case Sensitive ob Donald Duck oder DONALD DUCK ist egal beides funktioniert.
4: Wenn man beim erstellen eines Paketes beim Kommentar einen zu langen String (über 256 Zeichen) eingibt stürzt die Seite ab und erstellt kein Paket, wenn man dann aber zurück geht und es korrigiert wird dann ein Paket erstellt es wird aber eine ID übersprungen. Deutet darauf hin, dass wenn ein Fehler beim erstellen eines Paketes passiert trotzdem irgendwas geändert wird.
5: Wenn sich in zwei Tabs der gleiche User einloggen will stürzt die Seite ab anstatt eine Meldung zu geben, dass der User bereits eingeloggt ist.
6: Zuordnen des Pakets auf einen Fahrer macht noch nichts. (Aber das seit ihr euch ja sicher bewusst, eher ein fehlendes Feature)

**Comment by SamuelSchwegler** [comment]
Die verbliebenen Issues wurden in Neue übernommen
